name: quality_checks
on:
  push:
permissions:
  actions: write
  contents: read
jobs:
  all_checks:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: unit tests
        run: npm run coverage

      - name: e2e tests
        uses: cypress-io/github-action@v3
        with:
          start: npm run web
          wait-on: "http://localhost:19006"
        env:
          PORT: "19006"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}